services:
    app:
        build: .
        image: e-presence
        container_name: e-presence
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
        working_dir: /var/www/e-presence
        volumes:
            - '.:/var/www/e-presence'
            - './backend/storage/php.ini:/usr/local/etc/php/conf.d/local.ini'
        networks:
            - e-presence
    webserver:
        image: 'nginx:alpine'
        container_name: nginxepresence
        restart: unless-stopped
        tty: true
        ports:
            - '2025:80'
        volumes:
            - '.:/var/www/e-presence'
            - './backend/storage/:/etc/nginx/conf.d/'
        networks:
            - e-presence
    db:
        image: mysql
        container_name: dbepresence
        restart: always
        tty: true
        ports:
            - '2007:3306'
        volumes:
            - 'lbdata:/var/lib/mysql'
        environment:
            MYSQL_PASSWORD: raadeveloperz
            MYSQL_ROOT_PASSWORD: raadeveloperz
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - e-presence
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pmaepresence
        links:
            - db
        restart: always
        ports:
            - '7000:80'
        networks:
            - e-presence
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    e-presence:
        driver: bridge
volumes:
    lbdata:
        driver: local
    sail-mysql:
        driver: local
